### ISSUE TITLE
setSelection call missing

### ISSUE THREAD

**Issue by StefanKern** [angular-google-chart/angular-google-chart#294] opened 2016-10-18 15:52 UTC
How can I set the selection of a slice.

I found your "agcOnSelect" property, for getting the selected Slice and react to it, but I don't find any way to set the selection.

In the Google docs I found the `setSelection()` Method ((https://developers.google.com/chart/interactive/docs/gallery/piechart#methods)).

However I found no way, of accessing this function.

Thanks for your help.

**Comment by siddhartha-gupta** [comment] 2016-10-20 06:27
I'm working with multiple charts(pie charts) and on selecting one chart another chart should be un-selected. So to accomplish the same, here's what I did

- added agc-on-ready - http://angular-google-chart.github.io/angular-google-chart/docs/0.1.0/directives/agcOnReady/
- when the method is invoke, saved the 'chartWrapper' object on a scope variable
- when click function is triggered on any chart, you can access setSelection() using the 'chartWrapper' object

```
// this removed selection from the particular chart
$scope.chart1WrapperInstance.getChart().setSelection([]);
```

**Comment by HarelM** [comment] 2017-03-26 21:33
+1

**Comment by HarelM** [comment] 2017-03-31 20:41
@nbering can you direct me to the place in the code where one could implement this, I'll see if I can create a pull request?

**Comment by nbering** [comment] 2017-03-31 23:07
The above comment already demonstrates how this can be done. It's a work-around, but I'm not sure anything more complex need be implemented. Here's a more completed code sample that should do roughly the same. I haven't run this code - so there may be errors - but it's the concept that counts.

```html
<div ng-controller="ReportController as $ctrl">
    <div google-chart chart="$ctrl.salesChart" agc-on-ready="$ctrl.onSalesChartReady(chartWrapper)"></div>
    <div google-chart chart="$ctrl.revenueChart" agc-on-click="$ctrl.onRevenueChartClick()"></div>
</div>
```

```js
angular.module("app").controller("ReportController", ReportController);

function ReportController(){
    this.salesChartWrapper = null;
    this.revenueChartWrapper = null;

    this.onSalesChartReady = function(chartWrapper) {
        this.salesChartWrapper = chartWrapper;
    };

    this.onRevenueChartClick = function() {
        if (this.salesChartWrapper)
            this.salesChartWrapper.getChart().setSelection([]);
    };

    this.salesChart = {
        chartType: "LineChart",
        data: [],
        options: {}
    };

    this.revenueChart = {
        chartType: "AreaChart",
        data: [],
        options: {}
    };
}
```

Of course, within the above example, the chart wrapper instance remains in the controller... but there's nothing stopping you from having that method call save the instance to a service so you can fetch instances of the chart or chartWrapper across the application.

I would however caution that in doing so, there is a strong possibility that you would leak memory as you leave stale chart instances around as the user navigates through your application and chart directives are created and destroyed. You would want to provide a destroy handler for your service to clean up and chart instances it registered with the service.

**Comment by HarelM** [comment] 2017-04-01 22:11
Thanks for the code snippet, unfortunately I discovered that the concept of what I need to do will probably not work - I want the user to hover over a route he planned on a map and that the location in the route will be shown on an elevation chart. the problem is that the chart is hover is possible only on points while the route hover can be in between points.
Thanks anyway!

**Comment by nbering** [comment] 2017-04-01 22:21
As I understand it... the problem is that you can't represent a value between data points on the elevation graph? Have a look at this codepen example (I've gotten a lot of mileage out of this example).

http://codepen.io/nbering/pen/yNZxKr

It makes use of the chart layout interface to calculate the css position of a point relative to the data axes so that you can overlay any HTML element relative to the data in the chart. You could use this to interpolate the data coordinates of your elevation, and then place your own custom-styled marker there.

**Comment by nbering** [comment] 2017-04-15 02:32
Closing as aged/resolved.

**Closed by nbering** 2017-04-15 02:32 UTC
