### ISSUE TITLE
Question about injection

### ISSUE THREAD

**Issue by rixlabs** [angular-google-chart/angular-google-chart#240] opened 2015-12-03 11:03 UTC
I write here to keep track of the conversation.

I'm digging into the code trying to understand some details and I've got a low level question about the chartWrapper.

Looking at the link function of the agcOnReady directive:
```
 link: function(scope, element, attrs, googleChartController){
                callback.$inject=['chartWrapper'];
                function callback(chartWrapper){
                    scope.$apply(function (){
                        scope.$eval(attrs.agcOnReady, {chartWrapper: chartWrapper});
                    });
                }
                googleChartController.registerWrapperListener('ready', callback, this);
            }
```

I've noted that the chartWrapper is passed as local to the callback function indicated by attrs.agcOnReady.
And that's the clear part...my question is about the injection.
How does this work?
```
 callback.$inject=['chartWrapper'];
                function callback(chartWrapper){
...
```

Where did he find the original chartWrapper object'

I tryed to reconstruct but I didn't understand. Probably I don't understand how the $inject works.

If you have time to explain this or some good link that can explain this kind of behaviour I would be thankful.

Thanks in advance
Ric

**Comment by Balrog30** [comment] 2015-12-03 13:20
The chartWrapper is objective from the service class used by the main difective's controller.  This service class is effectively a controller, I refactored it into a service so that directive's that behave in different ways could be made easily in the future.  People were asking for custom features that were kind of one-off, so I thought it would be nice to move the logic out of the directive itself and make it more reusable.

I'll send you more details about where the injection actually occurs once I've had some coffee.  It's done with the $injector service if I remember correctly.  I originally wrote that back in April or May, and did the refactor in August/September.

**Comment by Balrog30** [comment] 2015-12-03 14:25
Ok. This was probably the most "clever" code I've written, so I apologize. I was having fun passing functions around as function arguments. I don't get to write this kind of code in my day job. :smiley:

[`src/googleChartService.js` line 154](https://github.com/angular-google-chart/angular-google-chart/blob/fa139db5bfb1c6c6686756cd66a565b2d013fae0/src/googleChartService.js#L154-L161)

```JavaScript
// This is the function that will be invoked by the charts API.
// Passing the wrapper function allows the use of DI for
// for the called function.
var listenerWrapper = function() {
    var locals = {
        chartWrapper: _chartWrapper,
        chart: _chartWrapper.getChart(),
        args: arguments
    };
    $injector.invoke(listenerFn, listenerObject || this, locals);
};
```

This little nugget handles the actual injection. When you register a event listener function with our library, it wraps the listenerFunction in `listenerWrapper`. `listenerWrapper` gets passed to Google's library and when it calls this, we call you with more details. `arguments` gets passed as `args` so that I can generically handle ANYTHING passed by google in the event directives. I added that very early on and never factored it out. I didn't need that because google only passes one object with keys for multiple return values. No need for `arguments`.

**Comment by Balrog30** [comment] 2015-12-03 14:40
# About the Angular $injector Service

While I'm on a roll here...

The $injector service does a `.toString()` on a function to get the name of the function arguments, and then injects the locals by name. Because minification can mangle the names of your arguments, to make your code minification safe, you can give Angular the string names of your arguments as strings. Minification won't mangle strings, you see.

There are two flavours of these annotations. Array notation, and $inject notation.

## Array Notation

You see a lot of this around. Very common when registering controllers and services. The problem is, it's kind of ugly.

```JavaScript
.controller("MyController", ["$scope", function ($scope){}]);
```

In theory, this should work when registering event listeners with Angular Google Chart, but I've never tested it to be sure.

## $inject Notation

`$inject` is just an array of strings telling the injector service what to pass. The only downside to this notation is that it doesn't work with Anonymous functions if you haven't stored them somewhere, because you need to hold onto the function object long enough to tack this key onto it.

```JavaScript
function myFunction(value){
};

myFunction.$inject = ["value"];
```

Note that functions that are not assigned with `var`, sometimes called named functions, are hoisted. So if you call the function BEFORE it was declared, that works just fine. I like this property of JavaScript, because it allows you to put all the important stuff at the top of your file, and bury anything else. That's why most of my functions are declared as named functions.

**Comment by rixlabs** [comment] 2015-12-03 15:38
OK, I think I begin to understand.

Still have some problem figuring out the execution times but I'm getting close to the point  

thanks a lot for the hints. I'll try to digest the info and maybe I'm not going to disturbe you again on the same subject :smile:

**Comment by rixlabs** [comment] 2015-12-03 15:41
I have to constantly remember that is the google library that orchestrate the thing...and this line:
```
googleChartController.registerWrapperListener('ready', callback, this);
```
with his **ready** event shud be enough :smile:

**Comment by rixlabs** [comment] 2015-12-03 16:04
as always R.T.F.M. is the solution:
[The array notation](https://docs.angularjs.org/api/auto/service/$injector#the-array-notation)

This section:
```
// We are forced to write break inlining
var tmpFn = function(obfuscatedCompile, obfuscatedRootScope) {
  // ...
};
tmpFn.$inject = ['$compile', '$rootScope'];
injector.invoke(tmpFn);
```

does the axact same thing without the locale thing.
The only thing that is still little abscure is the fact that the guide always speak about 'service' to inject and in this case is a locals coming from the wrapper.

p.s. my resolution about not disturbing you lasted 20 minutes

**Comment by Balrog30** [comment] 2015-12-03 16:14
Yes, you can use $injector to get your angular globals, and optionally pass locals. I used it for the locals feature. There's also a similar invoke-type function on $scope (I think it's `$scope.$eval`) which I'm using to call expression attributes on the directives. Same idea except that it works sort of the other way around. It give access to parent-scope stuff on the directive without needing it's own scope.

**Comment by rixlabs** [comment] 2015-12-03 16:28
:+1:  

Ok now I need some experimenting in my sandbox to fix all in my brain :smile: 

I'll open you another issue about the directives that uses the chartWrapper.

there are other ways to pass the arguments to the callback but they involve scope isolation.

**Comment by Balrog30** [comment] 2015-12-03 16:30
I was avoiding scope isolation because you can only have one scope per element, and I didn't want to fight with that when putting multiple directives on an element. Better just to avoid isolate scope altogether. It makes it a little more complicated, but it's been working pretty well.

**Comment by rixlabs** [comment] 2015-12-03 16:41
ok you can close the issue that I just opened  :grin: 
btw is not that complicated in the case I described in #241

**Comment by nbering** [comment] 2016-01-09 15:23
Thanks for the interesting discussion and contributions, @rixlabs, but I'm going to close this issue. Just cleaning up issues and this hasn't had any discussion in a while.

**Closed by nbering** 2016-01-09 15:23 UTC
Labels: documentation
