### ISSUE TITLE
OnSelect Doubt or Error

### ISSUE THREAD

**Issue by jnovaes** [angular-google-chart/angular-google-chart#210] opened 2015-08-24 05:22 UTC
I needed to put the code below because onSelect is not working :/

`
var tosend = { "selectedItem": selectedItem };    
`
`
$scope.onSelect()(tosend);
`
.....
![captura de tela 2015-08-24 as 02 15 26](https://cloud.githubusercontent.com/assets/4122376/9433272/765c931c-4a06-11e5-8caf-bf9bb6070718.png)

**Comment by Balrog30** [comment] 2015-08-24 05:39
I honestly have no idea what you're asking for here. If you're telling me it doesn't work for you, and this fixes your problem, then I need a lot more information.

Specifically, I need information on how to reproduce the error.  These details will help:

 * version of angular
 * version of angular-google-chart
 * browser and version (eg. Chrome version 42)
 * html and javascript example that reproduces the issue

All I can say without this information is that my own projects are using the version on master with no issues, and they do use `on-select`.

**Comment by Balrog30** [comment] 2015-08-31 05:07
My apologies, but I have not seen an issue with this, and cannot reproduce the issue without code that demonstrates how it was being used. 7 days have passed without more detail, so I am closing this issue. If it's any consolation, the next version will implement that feature in a completely different way, so the issue you were seeing probably won't be there.

**Closed by Balrog30** 2015-08-31 05:07 UTC
Labels: bug, needs information
