### ISSUE TITLE
Charts are not displayed on latest version of Firefox (43.0.4)

### ISSUE THREAD

**Issue by dipakbhimani** [angular-google-chart/angular-google-chart#255] opened 2016-01-25 10:40 UTC
Hi,

When I try to plot the charts on latest version of firefox (43.0.4), it not working. Blank screen is appearing.  However this is working on IE 11 and Chrome.

Any pointers to debug this issue will help.

**Comment by brencon** [comment] 2016-02-12 20:36
Same for me on Firefox 43.0.1.

**Comment by nbering** [comment] 2016-02-13 03:02
Sounds like a firefox or upstream Google Charts API bug. If you can be more specific about the types of charts you are plotting, that would help me investigate.  If you are setting the the chart api config value (loading packages, or changed version number), that would also be helpful to know. I'll look into it before I go to bed tonight, yet.

**Comment by nbering** [comment] 2016-02-13 03:14
I just downloaded and installed 43.0.1, and checked against the examples on http://angular-google-chart.github.io/angular-google-chart with no duplication of this issue. It worked fine, so I'll definitely need more information to reproduce this issue.

**Comment by brencon** [comment] 2016-02-13 14:34
My issue was occurring because of the GET to https://www.google.com/jsapi being blocked by an invalid security certificate error in Firefox:

> www.google.com uses an invalid security certificate.

>The certificate is not trusted because the issuer certificate is unknown.
The server might not be sending the appropriate intermediate certificates.
An additional root certificate may need to be imported.

>(Error code: sec_error_unknown_issuer)

As a workaround, I changed the protocol to "http:" on line 804 of ng-google-chart.js.

I was then able to render my charts in all browsers including Firefox.

Would it be possible to include the jsapi code locally within the library instead of returning the code via GET?

**Comment by nbering** [comment] 2016-02-13 18:21
No, we cannot include the code locally, as that is specifically against their terms of service. One of the roadmap issues is to change to their new loader, though, which would involve loading from a different endpoint and as such a different certificate. If you're getting certificate errors though, I would think there's something strange happening elsewhere (are you using an http debug proxy?). I'm not getting a certificate error even on the same version of Firefox, so there must be something else wrong.

**Comment by maniyarkj** [comment] 2016-03-02 11:42
Hi nbering,

As per mentioned by brencon, issue is with the https protocol, so without locally loading data, can we use just http in ng-google-chart.js ? or it's also against google's terms of service?

Thanks.

**Comment by nbering** [comment] 2016-03-02 14:07
I posted a little snippet in #259 that should allow you to switch to http without changing anything in the angular-google-chart library. Loading with http is not against terms of service, but downloading the code, saving it, and then serving it from another location is. They have said they're working to change those terms, but there's no urgent need to do so from their end so it'll probably take a while for that to change.

**Comment by nbering** [comment] 2017-04-15 02:19
Closing as aged.

**Closed by nbering** 2017-04-15 02:19 UTC
Labels: bug, needs information
